FROM node:20-alpine AS builder

ARG VITE_API_URL=/api
ARG VITE_MQTT_URL=ws://192.168.101.10:9001

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_MQTT_URL=$VITE_MQTT_URL

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine AS production
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
